version: 2
multi-ecosystem-groups:
  development:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    patterns:
      - "*"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 14
    allow:
      - dependency-type: "development"
    multi-ecosystem-group: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    cooldown:
      default-days: 30
    multi-ecosystem-group: "development"
